In [1]:

data = [
    {"time": 0, "temp": 32, "voltage": 400, "current": 20, "charge": 95},
    {"time": 1, "temp": 35, "voltage": 395, "current": 22, "charge": 88},
    {"time": 2, "temp": 38, "voltage": 390, "current": 25, "charge": 80},
    {"time": 3, "temp": 40, "voltage": 385, "current": 28, "charge": 70},
    {"time": 4, "temp": 42, "voltage": 380, "current": 30, "charge": 60},
    {"time": 5, "temp": 45, "voltage": 375, "current": 32, "charge": 48},
]

print("--- 1. Sensor Readings ---")
for row in data:
    print(
        f"Time: {row['time']}h | Temp: {row['temp']}°C | Voltage: {row['voltage']}V | Current: {row['current']}A | Charge: {row['charge']}%"
    )

print("\n--- 2. Temperature Alerts ---")
for row in data:
    if row["temp"] > 40:
        status = "High Temperature Alert"
    else:
        status = "Temperature Normal"
    print(f"Time {row['time']}h ({row['temp']}°C): {status}")

print("\n--- 3. Battery Charge Alerts ---")
for row in data:
    if row["charge"] < 50:
        status = "Low Battery Alert"
    else:
        status = "Battery Charge Normal"
    print(f"Time {row['time']}h ({row['charge']}%): {status}")


def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"


print("\n--- 4. Battery Status Categories ---")
for row in data:
    print(
        f"Time {row['time']}h (Charge: {row['charge']}%): Status = {battery_status(row['charge'])}"
    )

--- 1. Sensor Readings ---
Time: 0h | Temp: 32°C | Voltage: 400V | Current: 20A | Charge: 95%
Time: 1h | Temp: 35°C | Voltage: 395V | Current: 22A | Charge: 88%
Time: 2h | Temp: 38°C | Voltage: 390V | Current: 25A | Charge: 80%
Time: 3h | Temp: 40°C | Voltage: 385V | Current: 28A | Charge: 70%
Time: 4h | Temp: 42°C | Voltage: 380V | Current: 30A | Charge: 60%
Time: 5h | Temp: 45°C | Voltage: 375V | Current: 32A | Charge: 48%

--- 2. Temperature Alerts ---
Time 0h (32°C): Temperature Normal
Time 1h (35°C): Temperature Normal
Time 2h (38°C): Temperature Normal
Time 3h (40°C): Temperature Normal
Time 4h (42°C): High Temperature Alert
Time 5h (45°C): High Temperature Alert

--- 3. Battery Charge Alerts ---
Time 0h (95%): Battery Charge Normal
Time 1h (88%): Battery Charge Normal
Time 2h (80%): Battery Charge Normal
Time 3h (70%): Battery Charge Normal
Time 4h (60%): Battery Charge Normal
Time 5h (48%): Low Battery Alert

--- 4. Battery Status Categories ---
Time 0h (Charge: 95%): Status = 

In [2]:
import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

rows, cols = D.shape
print(f"1. Array Shape: {D.shape} -> Rows: {rows}, Columns: {cols}")

averages = np.mean(D, axis=0)
T_bar, V_bar, I_bar, C_bar = averages
print(f"2. Averages:")
print(f"   Average Temperature (T̄): {T_bar:.2f} °C")
print(f"   Average Voltage (V̄):     {V_bar:.2f} V")
print(f"   Average Current (Ī):     {I_bar:.2f} A")
print(f"   Average Charge (C̄):      {C_bar:.2f} %")

T_max = np.max(D[:, 0])
T_min = np.min(D[:, 0])
print(f"3. Temperature Range:")
print(f"   T_max: {T_max} °C")
print(f"   T_min: {T_min} °C")

V = D[:, 1:2]
print(f"4. Voltage Column Vector V:\n{V}")

high_temp_rows = D[D[:, 0] > 40]
print(f"5. High-Temperature Readings (T > 40 °C):\n{high_temp_rows}")

low_charge_rows = D[D[:, 3] < 50]
print(f"6. Low Battery Readings (C < 50 %):\n{low_charge_rows}")

1. Array Shape: (6, 4) -> Rows: 6, Columns: 4
2. Averages:
   Average Temperature (T̄): 38.67 °C
   Average Voltage (V̄):     387.50 V
   Average Current (Ī):     26.17 A
   Average Charge (C̄):      73.50 %
3. Temperature Range:
   T_max: 45 °C
   T_min: 32 °C
4. Voltage Column Vector V:
[[400]
 [395]
 [390]
 [385]
 [380]
 [375]]
5. High-Temperature Readings (T > 40 °C):
[[ 42 380  30  60]
 [ 45 375  32  48]]
6. Low Battery Readings (C < 50 %):
[[ 45 375  32  48]]


In [4]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
X_input = np.array([[40], [25]])
B = np.array([[100], [120]])

Y = np.dot(A, X_input)
A_transpose = A.T
det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)
X_solution = np.linalg.solve(A, B)

print(f"Y = AX:\n{Y}\n")
print(f"A^T:\n{A_transpose}\n")
print(f"det(A): {det_A:.2f}\n")
print(f"A^-1:\n{A_inv}\n")
print(f"Solution [x, y]:\n{X_solution}")

Y = AX:
[[105]
 [115]]

A^T:
[[2 1]
 [1 3]]

det(A): 5.00

A^-1:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution [x, y]:
[[36.]
 [28.]]
Y = AX:
[[105]
 [115]]

A^T:
[[2 1]
 [1 3]]

det(A): 5.00

A^-1:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution [x, y]:
[[36.]
 [28.]]


In [5]:
import sympy as sp

t = sp.Symbol('t')
C = 100 - 2*t - (1/2)*t**2

dC_dt = sp.diff(C, t)

rate_at_2 = dC_dt.subs(t, 2)
rate_at_5 = dC_dt.subs(t, 5)

print("--- Task 4: Calculus Analysis ---")
print(f"1. Derivative dC/dt = {dC_dt}")
print(f"2. Discharge rate at t = 2 hours: {rate_at_2}% per hour")
print(f"   Discharge rate at t = 5 hours: {rate_at_5}% per hour")


if dC_dt.diff(t) < 0:
    trend = "at an increasing rate"
elif dC_dt.diff(t) > 0:
    trend = "at a decreasing rate"
else:
    trend = "at a constant rate"

print(f"3. Interpretation: The battery is losing charge {trend}.")

--- Task 4: Calculus Analysis ---
1. Derivative dC/dt = -1.0*t - 2
2. Discharge rate at t = 2 hours: -4.00000000000000% per hour
   Discharge rate at t = 5 hours: -7.00000000000000% per hour
3. Interpretation: The battery is losing charge at an increasing rate.
